all: namedpipe1 namedpipe2 namedpipe3

namedpipe1: namedpipe1.c
	gcc -g -O0 -o namedpipe1 namedpipe1.c

namedpipe2: namedpipe2.c
	gcc -g -O0 -o namedpipe2 namedpipe2.c


namedpipe3: namedpipe3.c
	gcc -g -O0 -o namedpipe3 namedpipe3.c



clean:
	rm -rf *.o namedpipe1 namedpipe2 namedpipe3
