all: sig1 sig2 sig3 sig4 sig5 sig6 sig7

sig1: sig1.c
	gcc -g -O0 -o sig1 sig1.c

sig2: sig2.c
	gcc -g -O0 -o sig2 sig2.c

sig3: sig3.c
	gcc -g -O0 -o sig3 sig3.c

sig4: sig4.c
	gcc -g -O0 -o sig4 sig4.c

sig5: sig5.c
	gcc -g -O0 -o sig5 sig5.c

sig6: sig6.c
	gcc -g -O0 -o sig6 sig6.c

sig7: sig7.c
	gcc -g -O0 -o sig7 sig7.c


clean:
	rm -rf *.o sig1 sig2 sig3 sig4 sig5 sig6 sig7
