all: thr1 thr2 thr3 thr4 thr5 thr6 thr7

thr1: thr1.c
	gcc -g -O0 -o thr1 thr1.c -lpthread

thr2: thr2.c
	gcc -g -O0 -o thr2 thr2.c -lpthread

thr3: thr3.c
	gcc -g -O0 -o thr3 thr3.c -lpthread

thr4: thr4.c
	gcc -g -O0 -o thr4 thr4.c -lpthread

thr5: thr5.c
	gcc -g -O0 -o thr5 thr5.c -lpthread

thr6: thr6.c
	gcc -g -O0 -o thr6 thr6.c -lpthread

thr7: thr7.c
	gcc -g -O0 -o thr7 thr7.c -lpthread

clean:
	rm -rf *.o thr1 thr2 thr3 thr4 thr5 thr6 thr7
