all: sem1 sem2 sem3 sem4 sem5

sem1: sem1.c
	gcc -g -O0 -o sem1 sem1.c

sem2: sem2.c
	gcc -g -O0 -o sem2 sem2.c

sem3: sem3.c
	gcc -g -O0 -o sem3 sem3.c

sem4: sem4.c
	gcc -g -O0 -o sem4 sem4.c

sem5: sem5.c
	gcc -g -O0 -o sem5 sem5.c

clean:
	rm -rf *.o sem1 sem2 sem3 sem4 sem5
