all: tsem1 tsem2 tsem3 tsem4

tsem1: tsem1.c
	gcc -g -O0 -o tsem1 tsem1.c -lpthread

tsem2: tsem2.c
	gcc -g -O0 -o tsem2 tsem2.c -lpthread

tsem3: tsem3.c
	gcc -g -O0 -o tsem3 tsem3.c -lpthread

tsem4: tsem4.c
	gcc -g -O0 -o tsem4 tsem4.c -lpthread

clean:
	rm -rf *.o tsem1 tsem2 tsem3 tsem4
