all: mtx1 mtx2 mtx3 mtx4

mtx1: mtx1.c
	gcc -g -O0 -o mtx1 mtx1.c -lpthread

mtx2: mtx2.c
	gcc -g -O0 -o mtx2 mtx2.c -lpthread

mtx3: mtx3.c
	gcc -g -O0 -o mtx3 mtx3.c -lpthread

mtx4: mtx4.c
	gcc -g -O0 -o mtx4 mtx4.c -lpthread

clean:
	rm -rf *.o mtx1 mtx2 mtx3 mtx4
