all: malloc1 malloc2 malloc3 malloc4 malloc5 malloc6

malloc1: malloc1.c
	gcc -g -O0 -o malloc1 malloc1.c

malloc2: malloc2.c
	gcc -g -O0 -o malloc2 malloc2.c

malloc3: malloc3.c
	gcc -g -O0 -o malloc3 malloc3.c

malloc4: malloc4.c
	gcc -g -O0 -o malloc4 malloc4.c

malloc5: malloc5.c
	gcc -g -O0 -o malloc5 malloc5.c

malloc6: malloc6.c
	gcc -g -O0 -o malloc6 malloc6.c

clean:
	rm -rf *.o malloc1 malloc2 malloc3 malloc4 malloc5 malloc6
