all: ptrace1 ptrace2 ptrace3

ptrace1: ptrace1.c
	gcc -g -O0 -o ptrace1 ptrace1.c

ptrace2: ptrace2.c
	gcc -g -O0 -o ptrace2 ptrace2.c

ptrace3: ptrace3.c
	gcc -g -O0 -o ptrace3 ptrace3.c

clean:
	rm -rf *.o ptrace1 ptrace2 ptrace3
